apiVersion: v1
appVersion: "1.0"
description: A connector between commercetools and constructor.io
name: commercetools-constructorio-connector
version: 0.1.0
sources:
  - https://github.com/commercetools/blueprint