# Other environment variables may be specified here for consumption by deployment.yaml;
# Values.env and Values.secret are both exposed within the container as environment variables
name: [[service_name]]

env:
  EXPRESS_PORT: [[port]]

replicaCount: 1

image:
  repository: [[docker_image_url]]
  tag: [[docker_image_tag]]
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "kong"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: [[host]]
      paths:
        - /[[service_name]]
  tls:
    - secretName: [[service_name]]
      hosts:
      - [[host]]