apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # Pull env var values and secrets in values.yaml
          {{- if or $.Values.env $.Values.secrets }}
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.secrets }}
            - name: {{ $key | quote }}
              valueFrom:
                secretKeyRef:
                  key: {{ $key | quote }}
                  name: "{{ $.Release.Name }}-auth"
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.env.EXPRESS_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/isready
              port: http
            initialDelaySeconds: 15
            failureThreshold: 3
            periodSeconds: 20
            timeoutSeconds: 6
          readinessProbe:
            httpGet:
              path: /api/isready
              port: http
            initialDelaySeconds: 15
            failureThreshold: 2
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
