apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  # Inject (sensitive) environment variables from values.yaml config.
    {{- range $key, $val := .Values.secrets }}
    {{ $key }}: {{ $val | b64enc }}
    {{- end}}